routes/enterprises.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    redirect,
    url_for,
    flash,
)
from werkzeug.utils import secure_filename

from models.models import *

from utils.db import db

from utils.pictures import (
    random_name,
    remove_product_picture,
    remove_enterprise_picture,
)
from utils.services import *

enterprises = Blueprint("enterprises", __name__, url_prefix="/enterprises")


@enterprises.before_request
def before_request():
    if not "enterprise" in session:
        flash("Debes iniciar sessión", "auth_error")
        return redirect(url_for("auth.enterprise_login"))
    elif "enterprise" in session:
        global sessionUser
        global page_cant
        page_cant = 24
        sessionUser = Enterprises.query.filter_by(
            email=session["enterprise"]
        ).first()
        if sessionUser == None:
            session.pop("enterprise", None)
            flash("Ha ocurrido un error en los servidores 😕", "forbiden")
            return redirect(url_for("auth.enterprise_login"))
        elif sessionUser.level < 1:
            flash("Probablemente tu cuenta esta inhabilitada o betada 😕", "forbiden")
            return redirect(url_for("auth.enterprise_login"))


@enterprises.route("/homepage/<int:page_num>")
def homepage(page_num):
    products = Products.query.filter_by(enterprise_id=sessionUser.id).paginate(
        per_page=page_cant, page=page_num, error_out=True
    )
    for product in products:
        if product:
            print(products)

    images = Products_images.query.all()
    return render_template(
        "enterprises/panel/homepage.html",
        sessionUser=sessionUser,
        images=images,
        products=products
    )

@enterprises.route("/my-profile/update/description", methods=["POST"])
def update_description():
    back = request.referrer
    sessionUser.description = request.form["description"]
    db.session.commit()
    flash("Descripcion actualizada con exito", "success")
    return redirect(back)


# Funcion para detectar Extencion de archivo valido

ALLOWED_EXTENSIONS = set(["png", "jpg", "jpeg", "gif", "webp"])


def allowed_extensions(filename):
    return "." in filename and filename.rsplit(".", 1)[1] in ALLOWED_EXTENSIONS


@enterprises.route("/my-profile/logo", methods=["POST"])
def update_logo():
    back = request.referrer
    f = request.files["logo"]

    ext = f.filename.split(".")[1]
    username = sessionUser.username

    if f and allowed_extensions(f.filename):
        filename = secure_filename(random_name(username) + "." + ext)
        f.save("uploads/profile_pictures/enterprises/" + filename)
        update_enterprise_picture(username, filename)
        flash("Perfil actualizado exitosamente", "success")

        return redirect(back)

@enterprises.route("/product/create", methods=["GET", "POST"])
def product_create():
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        price = request.form["price"]
        enterprise_id = sessionUser.id
        new_product = Products(title, description, price, enterprise_id)
        db.session.add(new_product)
        db.session.commit()
        product = (
            Products.query.filter_by(enterprise_id=enterprise_id)
            .filter_by(title=title)
            .filter_by(description=description)
            .first()
        )

        # post photos
        session["actual_product"] = product.id

        files = request.files.getlist("files[]")
        i = 0
        for f in files:
            if f and allowed_extensions(f.filename):
                ext = f.filename.split(".")[1]
                filename = secure_filename(
                    random_name(str(session["actual_product"])) + str(i) + "." + ext
                )
                f.save("uploads/products_pictures/" + filename)
                i += 1
                new_photo = Products_images(filename, str(session["actual_product"]))
                db.session.add(new_photo)
                db.session.commit()

        session.pop("actual_product", None)
        flash("Producto Creado exitosamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))
    return render_template(
        "/enterprises/panel/products/create.html", sessionUser=sessionUser
    )


@enterprises.route("/product/delete/<id>", methods=["GET", "POST"])
def product_delete(id):
    product = Products.query.get(id)
    images = Products_images.query.filter_by(product_id=product.id).all()
    if request.method == "POST":
        for image in images:
            remove_product_picture(image.filename)
            db.session.delete(image)
            db.session.commit()
        db.session.delete(product)
        db.session.commit()
        flash("Producto eliminado satisfactoriamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))

    return render_template(
        "/enterprises/panel/products/delete.html",
        sessionUser=sessionUser,
        product=product,
        images=images
    )


@enterprises.route("/product/show/<id>")
def product_show(id):
    product = Products.query.get(id)
    images = Products_images.query.filter_by(product_id=product.id).all()

    return render_template(
        "/enterprises/panel/products/show.html",
        sessionUser=sessionUser,
        product=product,
        images=images
    )


@enterprises.route("/product/update/<id>", methods=["GET", "POST"])
def product_update(id):
    product = Products.query.get(id)
    if request.method == "POST":
        product.title = request.form["title"]
        product.description = request.form["description"]
        product.price = request.form["price"]
        product.enterprise_id = sessionUser.id
        db.session.commit()

        files = request.files.getlist("files[]")
        fi = Products_images.query.filter_by(product_id=product.id).first()

        if request.files.getlist("files[]") != None:
            i = 0
            for f in files:
                if f and allowed_extensions(f.filename):
                    ext = f.filename.split(".")[1]
                    filename = secure_filename(
                        random_name(str(product.id)) + str(i) + "." + ext
                    )
                    remove_product_picture(fi.filename)
                    fi.filename = filename
                    i += 1
                    f.save("uploads/products_pictures/" + filename)

                    db.session.commit()

        flash("Producto Actualizado exitosamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))
    return render_template(
        "/enterprises/panel/products/update.html",
        sessionUser=sessionUser,
        product=product
    )

templates/enterprises/panel/homepage.html
{% extends 'enterprise_base.html' %}
{% from '_render_elements.html' import render_input,render_paginate %}


{% block content %}

<div class="container-fluid contener">

    <div class="d-flex justify-content-center align-items-center mt-2">
        <div class="col-12">
            <h1 class="text-white text-center">Mis productos</h1>

            <div class="text-end">
                <a class="btn buttonB" href="{{url_for('enterprises.product_create')}}"><i
                        class="fa-solid fa-plus text-white"></i></a>
            </div>
            {% if products %}
            <div class="mt-2 col-12 d-flex flex-wrap">
                {% for product in products %}
                <a href="{{url_for('enterprises.product_show', id=product.id)}}" class="card-title product-title">
                    <div class="card col-3 rounded-3 product_card text-white mb-4"
                        style="margin-left:2rem !important; max-width:16rem;">

                        {% for image in images %}
                        {% if product.id == image.product_id %}
                        <div class="d-flex justify-content-center">
                            <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;"
                                src="{{ url_for('picture_products', filename=image.filename) }}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <p>{{product.title|truncate(40)}}</p>
                            <h4 class="fw-bold">
                                ${{product.price}}
                            </h4>

                        </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% if products.pages and products.page %}
<div class="d-flex col-12 justify-content-center align-items-center">
    {% if products.page != 1 %}
    <a href="{{ url_for('enterprises.homepage', page_num=products.prev_num ) }}"
        class="btn btn-outline-purple text-white">
        <i class="fa-solid fa-chevron-left"></i>
    </a>
    {% endif %}
    <p class="text-center mt-3 text-white" style="margin-right:0.5rem; margin-left:0.5rem;">
        <button class="btn buttonA disabled text-white">{{ products.page }}</button> de {{ products.pages }}
    </p>
    {% if products.page != products.pages %}
    <a href="{{ url_for('enterprises.homepage', page_num=products.next_num) }}"
        class="btn btn-outline-purple text-white">
        <i class="fa-solid fa-chevron-right"></i>
    {% endif %}
    </a>
  </div>
{% endif %}


{% else %}
<div class="mt-5 text-center col-12">
    <h3 class="opacity-50 text-white">No hay resultados...</h3>
</div>
{% endif %}

</div>
{% endblock content %}

templates/enterprises/panel/profile.html
{% if is_user==True %}
{% extends 'user_base.html' %}

{% else %}
{% extends 'enterprise_base.html' %}
{% endif %}
  
{% from "_render_elements.html" import render_input, render_messages %}


{% block content %}
<div class="container-fluid contener">

  <div class="d-flex justify-content-center">
    <div class="card shadow-lg col-10 mt-5 rounded-5" style="height:20%; margin-right:1rem !important; background:#7f4ca5;">
      <div class="card-body">

        <div class="d-flex justify-content-start">
          <div class="d-inline-flex">
            {% if enterprise.logo == None %}
            <img class="profile-img" src={{ url_for('static', filename='imgs/user_default.png' ) }} alt="">
            {% else %}
              <img class="profile-img" style="background: #887edd52;" src="{{ url_for('picture_enterprise_profile', filename=enterprise.logo) 
                  if enterprise.logo else 
                    url_for('picture_enterprise_profile', filename='user_default.png') 
                      }}" alt="">
            {% endif %}

            {% if sessionUser.id == enterprise.id and sessionUser.email == enterprise.email %}
            
            <form id="form" action="{{ url_for('enterprises.update_logo') }}" enctype='multipart/form-data'
              method="post">
              <input type="file" name="logo" id="file" class="inputfile" accept="image/png, image/jpeg">
              <label title="cambiar foto"
                style="margin-top:60px; margin-left:-36px; margin-right:5px; height:40px; width:40px;"
                class="btn Ebutton text-white rounded-circle" for="file">

                <i class="fa-solid fa-camera"></i>

              </label>
            </form>

            {% endif %}


          </div>
          <div class="mt-4 text-white col-11">
            <div class="d-flex row justify-content-between">
              <div class="col-10">
                <h5>{{enterprise.name}}</h5>
              </div>
              <div class="col-2 text-center d-none">
                <a href="#" title="Solicitar un cambio de nombre y/o nombre de usuario" style="height:38px; width:38px;"
                  class="btn shadow-lg Ebutton text-white "><i class="fa-solid fa-exclamation"></i></a>
              </div>
            </div>
            <h6 class="card-subtitle mb-2 opacity-75">{{enterprise.username}}</h6>
          </div>
        </div>

        <hr>

        <div>

          <p class="text-white opacity-75" style="font-size:14px; margin-bottom:0;">Descripcion</p>

          {% if enterprise.description == None or enterprise.description == '' %}

          <div class="d-flex justify-content-between row">

            <div class="col-6 mt-1">

              <span class="text-white" style="font-size:17px;" id="description">Aun no hay una descripcion
                añadida...</span>

            </div>
            <div class="col-xxl-2 col-lg-3 col-sm-4">
              {% if sessionUser.id == enterprise.id %}
              <button class="btn text-white Ebutton" id="editDescription"><i style="font-size:15px;"
                  class="fa-solid fa-pen"></i> Editar descripcion</button>
              {% endif %}
            </div>
          </div>

          <form class="d-none card" id="formDescription" style="border-color:rgba(0,0,0,0); background:rgba(0,0,0,0)"
            action="{{url_for('enterprises.update_description')}}" method="post">
            <div class="d-flex row justify-content-start">
              <div class="col-9">
                {{render_input('description','descripcion',value='',type='text',class='')}}
              </div>
              <div class="col-2" style="max-width:8rem;">
                {{render_input('','',value='Enviar',type='submit',class='btn btn-success ')}}
              </div>
              <button id="cancelDescription" class="btn btn-danger col-2" style="max-width:6.5rem;">Cancelar</button>
            </div>
          </form>

          {% else %}

          <div class="d-flex justify-content-between row">

            <div class="col-xxl-10 col-lg-9 col-sm-8 mt-1">

              <span class="text-white" style="font-size:17px;" id="description">{{enterprise.description}}</span>

            </div>

            <div class="col-xxl-2 col-lg-3 col-sm-4">
              {% if sessionUser.id == enterprise.id and sessionUser.email == enterprise.email %}
              <button class="btn text-white Ebutton" id="editDescription"><i style="font-size:15px;"
                  class="fa-solid fa-pen"></i> Editar descripcion</button>
              {% endif %}
            </div>

          </div>

          <form class="d-none card" id="formDescription" style="border-color:rgba(0,0,0,0); background:rgba(0,0,0,0)"
            action="{{url_for('enterprises.update_description')}}" method="post">
            <div class="d-flex row justify-content-start">
              <div class="col-8">
                <div class="form-floating">
                  <textarea maxlength="500" name="description" class="form-control" placeholder="Editando descripción"
                    id="floatingTextarea2" style="height: 80px">{{enterprise.description}}</textarea>
                  <label for="floatingTextarea2">Descripción</label>
                </div>
              </div>
              <div class="col-2" style="max-width:7rem;">
                {{render_input('','',value='Enviar',type='submit',class='btn btn-success ')}}
              </div>
              <div class="col-2">
                <button id="cancelDescription" class="btn btn-danger" style="max-width:8rem;">Cancelar</button>
              </div>
            </div>
          </form>

          {% endif %}

        </div>
      </div>
    </div>

  </div>
  <h1 class="text-center text-white mt-5 mb-5">Productos</h1>
  <div class="mt-2 ml-4 col-12 d-flex flex-wrap">
    {% for product in products %}
    <a href="{{url_for('enterprises.product_show', id=product.id)}}" class="card-title product-title">
        <div class="card col-3 rounded-3 product_card text-white mb-4"
            style="margin-left:2rem !important; max-width:16rem;">

            {% for image in images %}
            {% if product.id == image.product_id %}
            <div class="d-flex justify-content-center">
                <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;"
                src="{{ url_for('picture_products', filename=image.filename) }}" alt="">
            </div>
            {% endif %}
            {% endfor %}
            <div class="card-body">
                <p>{{product.title|truncate(40)}}</p>
                <h4 class="fw-bold">
                    ${{product.price}}
                </h4>

            </div>
    </a>
</div>
{% endfor %}

{% if products.pages and products.page %}

<div class="d-flex col-12 justify-content-center align-items-center">
  {% if products.page != 1 %}
  <a href="{{ url_for('enterprises.profile', id=enterprise.id ,page_num=products.prev_num ) }}"
  class="btn btn-outline-purple text-white">
  <i class="fa-solid fa-chevron-left"></i>
</a>
{% endif %}
    <p class="text-center mt-3 text-white" style="margin-right:0.5rem; margin-left:0.5rem;">
     <button class="btn buttonA disabled text-white">{{ products.page }}</button> de {{ products.pages }}
    </p>
    {% if products.page != products.pages %}
    <a href="{{ url_for('enterprises.profile', id=enterprise.id ,page_num=products.next_num) }}"
    class="btn btn-outline-purple text-white">
    <i class="fa-solid fa-chevron-right"></i>
    {% endif %}
  </a>
</div>
{% endif %}

</div>

<script>
  const description = document.getElementById('description');
  const editDescription = document.getElementById('editDescription');
  const formDescription = document.getElementById('formDescription');
  const cancelDescription = document.getElementById('cancelDescription');

  editDescription.addEventListener('click', () => {
    description.classList.add('d-none')
    editDescription.classList.add('d-none')
    formDescription.classList.remove('d-none')
  });

  cancelDescription.addEventListener('click', (e) => {
    description.classList.remove('d-none')
    editDescription.classList.remove('d-none')
    formDescription.classList.add('d-none')
    e.preventDefault()
  });

  document.getElementById("file").onchange = function () {
    document.getElementById("form").submit();
  };



</script>
{% endblock content %}