routes/users.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    redirect,
    url_for,
    flash,
)
from werkzeug.utils import secure_filename

from models.models import *

from utils.db import db

from utils.pictures import (
    random_name,
    remove_product_picture,
    remove_user_picture,
)
from utils.services import *

users = Blueprint('users',__name__, url_prefix="/users")

@users.before_request
def before_request():
    if not "user" in session:
        flash("Debes iniciar sessión", "auth_error")
        return redirect(url_for("auth.enterprise_login"))
    elif "user" in session:
        global page_cant
        page_cant = 24
        global sessionUser
        sessionUser = Users.query.filter_by(
            email=session["user"]
        ).first()
        if sessionUser == None:
            session.pop("user", None)
            flash("Ha ocurrido un error en los servidores 😕", "forbiden")
            return redirect(url_for("user_login"))
        elif sessionUser.level < 1:
            flash("Probablemente tu cuenta esta inhabilitada o betada 😕", "forbiden")
            return redirect(url_for("user_login"))

@users.route('/homepage/<int:page_num>')
def homepage(page_num):
    products = Products.query.paginate(
        per_page=page_cant, page=page_num, error_out=True
    )
    images = Products_images.query.all()
    enterprises = Enterprises.query.all()
    return render_template('/users/panel/homepage.html', sessionUser = sessionUser,enterprises=enterprises, products=products, images=images)

@users.route("/my-profile/update/description", methods=["POST"])
def update_description():
    back = request.referrer
    sessionUser.description = request.form["description"]
    db.session.commit()
    flash("Descripcion actualizada con exito", "success")
    return redirect(back)


# Funcion para detectar Extencion de archivo valido

ALLOWED_EXTENSIONS = set(["png", "jpg", "jpeg", "gif", "webp"])


def allowed_extensions(filename):
    return "." in filename and filename.rsplit(".", 1)[1] in ALLOWED_EXTENSIONS


@users.route("/my-profile/logo", methods=["POST"])
def update_logo():
    back = request.referrer
    f = request.files["logo"]

    ext = f.filename.split(".")[1]
    dni = sessionUser.dni

    if f and allowed_extensions(f.filename):
        filename = secure_filename(random_name(dni) + "." + ext)
        f.save("uploads/profile_pictures/users/" + filename)
        update_user_picture(dni, filename)
        flash("Perfil actualizado exitosamente", "success")

        return redirect(back)

templates/users/panel/homepage.html
{% extends 'user_base.html' %}
{% block content %}

<div class="container-fluid contener">

    <div class="d-flex justify-content-center align-items-center mt-2">
        <div class="col-12">
            <h1 class="text-white text-center mb-4 mt-2">Productos <i class="fa-solid fa-shield-cat"></i></h1>
            {% if products %}
            <div class="mt-2 col-12 d-flex flex-wrap">
                {% for product in products %}
                <a href="{{url_for('product_show', id=product.id)}}" class="card-title product-title">
                    <div class="card col-3 rounded-3 product_card text-white mb-4"
                        style="margin-left:2rem !important; max-width:16rem;">

                        {% for image in images %}
                        {% if product.id == image.product_id %}
                        <div class="d-flex justify-content-center">
                            <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;"
                                src="{{ url_for('picture_products', filename=image.filename) }}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <p>{{product.title|truncate(40)}}</p>
                            {% for enterprise in enterprises %}
                            
                            {% if product.enterprise_id == enterprise.id %}
                            <div class="mb-2 mt-2">
                                <a href="{{ url_for('profile',id=product.enterprise_id,page_num=1) }}" class="text-white fw-bold text-decoration-none">{{enterprise.name}}</a>
                            </div>
                            {% endif %}
                                
                            {% endfor %}    
                            <h4 class="fw-bold">
                                ${{product.price}}
                            </h4>

                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    
    {% if products.pages and products.page %}
    <div class="d-flex col-12 justify-content-center align-items-center">
        {% if products.page != 1 %}
        <a href="{{ url_for('users.homepage', page_num=products.prev_num ) }}"
        class="btn btn-outline-purple text-white">
        <i class="fa-solid fa-chevron-left"></i>
    </a>
    {% endif %}
    <p class="text-center mt-3 text-white" style="margin-right:0.5rem; margin-left:0.5rem;">
        <button class="btn buttonA disabled text-white">{{ products.page }}</button> de {{ products.pages }}
    </p>
    {% if products.page != products.pages %}
    <a href="{{ url_for('users.homepage', page_num=products.next_num) }}"
    class="btn btn-outline-purple text-white">
    <i class="fa-solid fa-chevron-right"></i>
    {% endif %}
</a>
</div>
{% endif %}


{% else %}
<div class="mt-5 text-center col-12">
    <h3 class="opacity-50 text-white">No hay resultados...</h3>
</div>
{% endif %}
</div>

{% endblock content %}

templates/users/panel/profile.html
{% if is_user==True %}
{% extends 'user_base.html' %}

{% else %}
{% extends 'enterprise_base.html' %}
{% endif %}
  
{% from "_render_elements.html" import render_input, render_messages %}


{% block content %}
<div class="container-fluid contener">

  <div class="d-flex justify-content-center">
    <div class="card shadow-lg col-10 mt-5 rounded-5" style="height:20%; margin-right:1rem !important; background:#7f4ca5;">
      <div class="card-body">

        <div class="d-flex justify-content-start">
          <div class="d-inline-flex">

            {% if user.logo == None %}
            <img class="profile-img" src={{ url_for('static', filename='imgs/user_default.png' ) }} alt="">
            {% else %}
            <img class="profile-img" src="{{ url_for('picture_user_profile', filename=user.logo) 
                                  if user.logo else 
                                  url_for('picture_profile', filename='none') 
                              }}" alt="">
            {% endif %}

            {% if sessionUser.id == user.id and sessionUser.email == user.email %}
            
            <form id="form" action="{{ url_for('users.update_logo') }}" enctype='multipart/form-data'
              method="post">
              <input type="file" name="logo" id="file" class="inputfile" accept="image/png, image/jpeg">
              <label title="cambiar foto"
                style="margin-top:60px; margin-left:-36px; margin-right:5px; height:40px; width:40px;"
                class="btn Ebutton text-white rounded-circle" for="file">

                <i class="fa-solid fa-camera"></i>

              </label>
            </form>

            {% endif %}


          </div>
          <div class="mt-4 text-white col-11">
            <div class="d-flex row justify-content-between">
              <div class="col-10">
                <h5>{{user.name}}</h5>
              </div>
              <div class="col-2 text-center d-none">
                <a href="#" title="Solicitar un cambio de nombre y/o nombre de usuario" style="height:38px; width:38px;"
                  class="btn shadow-lg Ebutton text-white "><i class="fa-solid fa-exclamation"></i></a>
              </div>
            </div>
            <h6 class="card-subtitle mb-2 opacity-75">{{user.username}}</h6>
          </div>
        </div>

        <hr>

        <div>

          <p class="text-white opacity-75" style="font-size:14px; margin-bottom:0;">Descripcion</p>

          {% if user.description == None or user.description == '' %}

          <div class="d-flex justify-content-between row">

            <div class="col-6 mt-1">

              <span class="text-white" style="font-size:17px;" id="description">Aun no hay una descripcion
                añadida...</span>

            </div>
            <div class="col-xxl-2 col-lg-3 col-sm-4">
              {% if sessionUser.id == user.id %}
              <button class="btn text-white Ebutton" id="editDescription"><i style="font-size:15px;"
                  class="fa-solid fa-pen"></i> Editar descripcion</button>
              {% endif %}
            </div>
          </div>

          <form class="d-none card" id="formDescription" style="border-color:rgba(0,0,0,0); background:rgba(0,0,0,0)"
            action="{{url_for('users.update_description')}}" method="post">
            <div class="d-flex row justify-content-start">
              <div class="col-9">
                {{render_input('description','descripcion',value='',type='text',class='')}}
              </div>
              <div class="col-2" style="max-width:8rem;">
                {{render_input('','',value='Enviar',type='submit',class='btn btn-success ')}}
              </div>
              <button id="cancelDescription" class="btn btn-danger col-2" style="max-width:6.5rem;">Cancelar</button>
            </div>
          </form>

          {% else %}

          <div class="d-flex justify-content-between row">

            <div class="col-xxl-10 col-lg-9 col-sm-8 mt-1">

              <span class="text-white" style="font-size:17px;" id="description">{{user.description}}</span>

            </div>

            <div class="col-xxl-2 col-lg-3 col-sm-4">
              {% if sessionUser.id == user.id and sessionUser.email == user.email %}
              <button class="btn text-white Ebutton" id="editDescription"><i style="font-size:15px;"
                  class="fa-solid fa-pen"></i> Editar descripcion</button>
              {% endif %}
            </div>

          </div>

          <form class="d-none card" id="formDescription" style="border-color:rgba(0,0,0,0); background:rgba(0,0,0,0)"
            action="{{url_for('users.update_description')}}" method="post">
            <div class="d-flex row justify-content-start">
              <div class="col-8">
                <div class="form-floating">
                  <textarea maxlength="500" name="description" class="form-control" placeholder="Editando descripción"
                    id="floatingTextarea2" style="height: 80px">{{user.description}}</textarea>
                  <label for="floatingTextarea2">Descripción</label>
                </div>
              </div>
              <div class="col-2" style="max-width:7rem;">
                {{render_input('','',value='Enviar',type='submit',class='btn btn-success ')}}
              </div>
              <div class="col-2">
                <button id="cancelDescription" class="btn btn-danger" style="max-width:8rem;">Cancelar</button>
              </div>
            </div>
          </form>

          {% endif %}

        </div>
      </div>
    </div>

  </div>

</div>

<script>
  const description = document.getElementById('description');
  const editDescription = document.getElementById('editDescription');
  const formDescription = document.getElementById('formDescription');
  const cancelDescription = document.getElementById('cancelDescription');

  editDescription.addEventListener('click', () => {
    description.classList.add('d-none')
    editDescription.classList.add('d-none')
    formDescription.classList.remove('d-none')
  });

  cancelDescription.addEventListener('click', (e) => {
    description.classList.remove('d-none')
    editDescription.classList.remove('d-none')
    formDescription.classList.add('d-none')
    e.preventDefault()
  });

  document.getElementById("file").onchange = function () {
    document.getElementById("form").submit();
  };



</script>
{% endblock content %}