routes/enterprises.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    redirect,
    url_for,
    flash,
)
from werkzeug.utils import secure_filename

from models.models import *

from utils.db import db

from utils.pictures import (
    random_name,
    remove_product_picture,
    remove_enterprise_picture,
)
from utils.services import *

enterprises = Blueprint("enterprises", __name__, url_prefix="/enterprises")


@enterprises.before_request
def before_request():
    if not "enterprise" in session:
        flash("Debes iniciar sessión", "auth_error")
        return redirect(url_for("auth.enterprise_login"))
    elif "enterprise" in session:
        global sessionUser
        global page_cant
        page_cant = 24
        sessionUser = Enterprises.query.filter_by(
            email=session["enterprise"]
        ).first()
        if sessionUser == None:
            session.pop("enterprise", None)
            flash("Ha ocurrido un error en los servidores 😕", "forbiden")
            return redirect(url_for("auth.enterprise_login"))
        elif sessionUser.level < 1:
            flash("Probablemente tu cuenta esta inhabilitada o betada 😕", "forbiden")
            return redirect(url_for("auth.enterprise_login"))


@enterprises.route("/homepage/<int:page_num>")
def homepage(page_num):
    products = Products.query.filter_by(enterprise_id=sessionUser.id).paginate(
        per_page=page_cant, page=page_num, error_out=True
    )
    for product in products:
        if product:
            print(products)

    images = Products_images.query.all()
    return render_template(
        "enterprises/panel/homepage.html",
        sessionUser=sessionUser,
        images=images,
        products=products
    )

@enterprises.route("/my-profile/update/description", methods=["POST"])
def update_description():
    back = request.referrer
    sessionUser.description = request.form["description"]
    db.session.commit()
    flash("Descripcion actualizada con exito", "success")
    return redirect(back)


# Funcion para detectar Extencion de archivo valido

ALLOWED_EXTENSIONS = set(["png", "jpg", "jpeg", "gif", "webp"])


def allowed_extensions(filename):
    return "." in filename and filename.rsplit(".", 1)[1] in ALLOWED_EXTENSIONS


@enterprises.route("/my-profile/logo", methods=["POST"])
def update_logo():
    back = request.referrer
    f = request.files["logo"]

    ext = f.filename.split(".")[1]
    username = sessionUser.username

    if f and allowed_extensions(f.filename):
        filename = secure_filename(random_name(username) + "." + ext)
        f.save("uploads/profile_pictures/enterprises/" + filename)
        update_enterprise_picture(username, filename)
        flash("Perfil actualizado exitosamente", "success")

        return redirect(back)

@enterprises.route("/product/create", methods=["GET", "POST"])
def product_create():
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        price = request.form["price"]
        enterprise_id = sessionUser.id
        new_product = Products(title, description, price, enterprise_id)
        db.session.add(new_product)
        db.session.commit()
        product = (
            Products.query.filter_by(enterprise_id=enterprise_id)
            .filter_by(title=title)
            .filter_by(description=description)
            .first()
        )

        # post photos
        session["actual_product"] = product.id

        files = request.files.getlist("files[]")
        i = 0
        for f in files:
            if f and allowed_extensions(f.filename):
                ext = f.filename.split(".")[1]
                filename = secure_filename(
                    random_name(str(session["actual_product"])) + str(i) + "." + ext
                )
                f.save("uploads/products_pictures/" + filename)
                i += 1
                new_photo = Products_images(filename, str(session["actual_product"]))
                db.session.add(new_photo)
                db.session.commit()

        session.pop("actual_product", None)
        flash("Producto Creado exitosamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))
    return render_template(
        "/enterprises/panel/products/create.html", sessionUser=sessionUser
    )


@enterprises.route("/product/delete/<id>", methods=["GET", "POST"])
def product_delete(id):
    product = Products.query.get(id)
    images = Products_images.query.filter_by(product_id=product.id).all()
    if request.method == "POST":
        for image in images:
            remove_product_picture(image.filename)
            db.session.delete(image)
            db.session.commit()
        db.session.delete(product)
        db.session.commit()
        flash("Producto eliminado satisfactoriamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))

    return render_template(
        "/enterprises/panel/products/delete.html",
        sessionUser=sessionUser,
        product=product,
        images=images
    )


@enterprises.route("/product/show/<id>")
def product_show(id):
    product = Products.query.get(id)
    images = Products_images.query.filter_by(product_id=product.id).all()

    return render_template(
        "/enterprises/panel/products/show.html",
        sessionUser=sessionUser,
        product=product,
        images=images
    )


@enterprises.route("/product/update/<id>", methods=["GET", "POST"])
def product_update(id):
    product = Products.query.get(id)
    if request.method == "POST":
        product.title = request.form["title"]
        product.description = request.form["description"]
        product.price = request.form["price"]
        product.enterprise_id = sessionUser.id
        db.session.commit()

        files = request.files.getlist("files[]")
        fi = Products_images.query.filter_by(product_id=product.id).first()

        if request.files.getlist("files[]") != None:
            i = 0
            for f in files:
                if f and allowed_extensions(f.filename):
                    ext = f.filename.split(".")[1]
                    filename = secure_filename(
                        random_name(str(product.id)) + str(i) + "." + ext
                    )
                    remove_product_picture(fi.filename)
                    fi.filename = filename
                    i += 1
                    f.save("uploads/products_pictures/" + filename)

                    db.session.commit()

        flash("Producto Actualizado exitosamente", "success")
        return redirect(url_for("enterprises.homepage", page_num=1))
    return render_template(
        "/enterprises/panel/products/update.html",
        sessionUser=sessionUser,
        product=product
    )

templates/enterprises/panel/products/create.html
{% extends 'enterprise_base.html' %}
{% from '_render_elements.html' import render_input %}


{% block content %}
<div class="d-flex justify-content-center">
    <div class="card shadow-lg col-8 mt-5 rounded-5" style="height:20%; background:#7f4ca5;">
        <div class="card-body">
            <form action="{{url_for('enterprises.product_create')}}" enctype="multipart/form-data" method="post">

                <h3 class="text-center text-white">Crear nuevo producto</h3>
                <div class="col-12">
                    <label for="" class="text-white">Titulo del producto</label>
                    {{render_input('title','','',type='text',class='')}}
                </div>
                <div class="col-12 mt-2">
                    <div class="form-floating">
                        <span class="text-white fw-bold">Descripcion</span>
                        <textarea maxlength="500" name="description" class="form-control"
                            placeholder="Editando descripción" id="floatingTextarea2" style="height: 80px"></textarea>
                    </div>
                </div>
                <div>
                    <div class="col-12">
                        <label for="" class="text-white">Precio (en dolares $)</label>
                        {{render_input('price','','',type='Number',class='')}}
                    </div>
                    <div class="mb-2 mt-2">
                        <label for="formFile" class="form-label text-white">Foto del producto</label>
                        <input class="form-control" name="files[]" type="file" id="formFile">
                        <!-- <label for="formFileMultiple" class="fw-bold text-white">Fotos del producto</label>
                        <input class="form-control" type="file" name="files[]" required accept="image/png, image/jpeg, image/webp"
                             id="formFileMultiple" multiple>  -->
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <div class="col-2 mt-3">
                        {{render_input('','','Crear',type='submit',class='btn buttonA text-white') }}
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

templates/enterprises/panel/products/delete.html
{% extends 'enterprise_base.html' %}
{% from '_render_elements.html' import render_input %}


{% block content %}
<div class="d-flex justify-content-center">
    <div class="card shadow-lg col-10 mt-5 rounded-5" style="height:20%; background:#7f4ca5;">
        <div class="card-body">
            <h4 class="text-white text-center mb-4">Seguro que desea borrar este producto</h4>
            <p style="font-size:17px;" class="text-white text-center">estas apunto de borrar el producto: <b>{{product.title}}</b>. despues de eliminarlo
                no se podra recuperar seguro que quiere proseguir con la eliminacion de dicho producto?
            </p>
            <div class="col-12 d-flex justify-content-between">
                <div class="">
                    <a class="btn btn-primary" href="{{url_for('enterprises.homepage', page_num=1)}}">Cancelar</a>
                </div>
                <div>
                    <form action="{{url_for('enterprises.product_delete', id = product.id)}}" method="post">
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/enterprises/panel/products/show.html
{% if is_user==True %}
{% extends 'user_base.html' %}
{% else %}
{% extends 'enterprise_base.html' %}
{% endif %}
{% from '_render_elements.html' import render_input %}


{% block content %}
<div class="container-fluid contener">
  <div class="d-flex col-12 justify-content-start align-items-start mt-3" style="background:#7f4ca5;">

    <div class="col-6 p-5" style="background:#8d56b8;">
      {% for image in images %}
      <img class="col-12" style="height:30rem !important; object-fit:scale-down; border-radius:0;" src="{{ url_for('picture_products', filename=image.filename) }}" alt="">
      {% endfor %}
    </div>
    
    <div class="col-6 text-white mt-5 p-5">
      <div class="d-flex justify-content-between mt-5 mb-5">
    {% if sessionUser.id == product.enterprise_id and sessionUser.email == enterprise.email%}
        <a class="btn btn-success text-white" style="margin-left:2rem !important;" href="{{url_for('enterprises.product_update', id = product.id)}}">Editar</a>
        <a class="btn darkred text-white" style="margin-right:2rem !important;" href="{{url_for('enterprises.product_delete', id = product.id)}}">Borrar</a>
        {% endif %}
      </div>
      
      <div class="mt-5 text-break" style="margin-left:2rem !important; margin-right:2rem !important;">
        <h4 class="col-12">{{product.title}}</h4>
        <p style="font-size: 1.1rem;" class="col-12 mt-3">{{product.description}}</p>
        <h2>${{product.price}}</h2>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/enterprises/panel/products/update.html
{% extends 'enterprise_base.html' %}
{% from '_render_elements.html' import render_input %}


{% block content %}
<div class="d-flex justify-content-center">
    <div class="card shadow-lg col-8 mt-5 rounded-5" style="height:20%; background:#7f4ca5;">
        <div class="card-body">
            <form action="{{url_for('enterprises.product_update', id=product.id)}}" enctype="multipart/form-data" method="post">

                <h3 class="text-center text-white">Editar producto</h3>
                <div class="col-12">
                    <label for="" class="text-white">Titulo del producto</label>
                    {{render_input('title',value=product.title,type='text',class='')}}
                </div>
                <div class="col-12 mt-2">
                    <div class="form-floating">
                        <span class="text-white fw-bold">Descripcion</span>
                        <textarea maxlength="500" name="description" class="form-control"
                            placeholder="Editando descripción" id="floatingTextarea2" style="height: 80px">{{product.description}}</textarea>
                    </div>
                </div>
                <div>
                    <div class="col-12">
                        <label for="" class="text-white">Precio (en dolares $)</label>
                        {{render_input('price',value=product.price,type='Number',class='')}}
                    </div>
                    <div class="mb-2 mt-2">
                        <label for="formFile" class="form-label text-white">Foto del producto (Si no desea cambiarla no introduzca nada)</label>
                        <input class="form-control" name="files[]" type="file" id="formFile">
                        <!-- <label for="formFileMultiple" class="fw-bold text-white">Fotos del producto</label>
                        <input class="form-control" type="file" name="files[]" required accept="image/png, image/jpeg, image/webp"
                             id="formFileMultiple" multiple>  -->
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <div class="col-2 mt-3">
                        {{render_input('','','Editar',type='submit',class='btn buttonA text-white') }}
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}