routes/auth.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from passlib.hash import sha256_crypt
from utils.db import db
from models.models import Countries, States, Users, Enterprises

auth = Blueprint("auth", __name__, url_prefix="/auth")


# Users authentication


@auth.route("/users/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        name = request.form["name"]
        lastname = request.form["lastname"]
        dni = request.form["dni"]
        email = request.form["email"]
        password = request.form["password"]
        country_id = request.form["country_id"]
        state_id = request.form["state_id"]

        hashed_pw = sha256_crypt.hash(request.form["password"])
        new_user = Users(name, lastname, dni, email, hashed_pw, country_id, state_id)

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for("auth.login"))

    countries = Countries.query.all()
    states = States.query.all()
    return render_template(
        "/users/auth/signup.html", countries=countries, states=states
    )


@auth.route("/users/login", methods=["GET", "POST"])
def user_login():
    if request.method == "POST":
        user = Users.query.filter_by(email=request.form["email"]).first()
        if user and sha256_crypt.verify(request.form["password"], user.password):
            session["user"] = user.email
            if user.level == 10:
                return redirect(url_for("admin.countries", page_num=1))
            else:
                return redirect(url_for("users.homepage", page_num=1))
        else:
            flash(
                "Credenciales invalidas por favor verifique e intentelo de nuevo",
                "error",
            )
            return redirect(url_for("auth.user_login"))

    return render_template("/users/auth/login.html")


@auth.route("/user/logout")
def logout():
    session.pop("user", None)

    return redirect(url_for("auth.user_login"))


# Enterprises authentication


@auth.route("/enterprises/signup", methods=["GET", "POST"])
def enterprise_signup():
    enterprises = Enterprises.query.all()
    if request.method == "POST":
        name = request.form["name"]
        error = [False, False, False]

        for enterprise in enterprises:

            if enterprise.username == "@" + request.form["username"]:
                error[0] = True

            elif enterprise.email == request.form["email"]:
                error[1] = True

            elif enterprise.dni == request.form["dni"]:
                error[2] = True

        if error[0] == False and error[1] == False and error[2] == False:
            username = "@" + request.form["username"]
            email = request.form["email"]
            dni = request.form["dni"]

        elif error[0] == True:
            flash("Nombre de usuario no disponible", "error")
            return redirect(url_for("auth.enterprise_signup"))

        elif error[1] == True:
            flash("Correo electronico no disponible", "error")
            return redirect(url_for("auth.enterprise_signup"))

        elif error[2] == True:
            flash("Dni no disponible", "error")
            return redirect(url_for("auth.enterprise_signup"))

        password = request.form["password"]
        country_id = request.form["country_id"]
        state_id = request.form["state_id"]

        hashed_pw = sha256_crypt.hash(request.form["password"])
        new_enterprise = Enterprises(
            name, username, dni, email, hashed_pw, country_id, state_id
        )

        db.session.add(new_enterprise)
        db.session.commit()

        return redirect(url_for("auth.enterprise_login"))

    countries = Countries.query.all()
    states = States.query.all()
    return render_template(
        "/enterprises/auth/signup.html", countries=countries, states=states
    )


@auth.route("/enterprises/login", methods=["GET", "POST"])
def enterprise_login():
    if request.method == "POST":
        enterprise = Enterprises.query.filter_by(email=request.form["email"]).first()
        if enterprise and sha256_crypt.verify(
            request.form["password"], enterprise.password
        ):
            session["enterprise"] = enterprise.email
            return redirect(url_for("enterprises.homepage" , page_num=1))
        else:
            flash(
                "Credenciales invalidas por favor verifique e intentelo de nuevo",
                "error",
            )
            return redirect(url_for("auth.enterprise_login"))
    if "enterprise" in session:
        return redirect(url_for("enterprises.homepage", page_num=1))
    else:
        return render_template("/enterprises/auth/login.html")


@auth.route("/enterprise/logout")
def enterprise_logout():
    session.pop("enterprise", None)

    return redirect(url_for("auth.enterprise_login"))

templates/_render_elements.html
{% macro render_input(name,placeholder,value,type='text',class='form-control',id="") %}
<input required name="{{name}}" placeholder="{{placeholder}}" value="{{value}}" type="{{type}}"
  class="form-control {{class}}" id="{{id}}">
{% endmacro %}

{% macro render_messages(messages) %}
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}

<div class="d-flex container justify-content-center">
  <ul class="card col-10 mt-4 rounded-3 text-white mb-4" style="background: #8d56b8;" id="uli">
    {% for category, message in messages %}
    
    <li class="text-white mt-2 mb-2 {{ category }}">{{ message }}</li>
    
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endwith %}
<script>
  document.getElementById('uli')
  
  const timer = 1800;
  setTimeout(() => {
      uli.classList.add('d-none');
  }, timer)
</script>
{% endmacro %}

templates/admin_base.html
{% from '_render_elements.html' import render_messages %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href={{ url_for('static', filename='css/sidebar.css' ) }}>
  <link rel="stylesheet" href={{ url_for('static', filename='css/style.css' ) }}>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  
  
  <div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    <div class="border-end bg-purple no-border" id="sidebar-wrapper">
      <div class="sidebar-heading border-bottom bg-purple no-border text-white">
        <img width="180px" height="80px" src={{ url_for('static', filename='imgs/logo-white.png' ) }} alt="">
      </div>
      <div class="list-group list-group-flush contener-1">

        <div>
          <a class="list-group-item list-group-item-action no-border bg-Dpurple list-group-item-light p-3 text-white"
            role="button" href="#collapse1" data-bs-toggle="collapse" aria-controls="collapse1" aria-expanded="false">
            ><b>Ubicaciones</b> <i class="fa-solid fa-earth-americas"></i>
          </a>
        </div>
        <div class="collapse" id="collapse1">
          <a class="list-group-item list-group-item-action text-white bg-Lpurple list-group-item-light p-3 collapse-animation"
            href="{{ url_for('admin.countries', page_num=1)}}">
            <b>> Paises</b>
          </a>
          <a class="list-group-item list-group-item-action text-white bg-Lpurple list-group-item-light p-3 collapse-animation"
          href="{{ url_for('admin.states', page_num=1)}}">
            <b>> Estados</b>
          </a>
        </div>
        
        <div>
          <a class="list-group-item list-group-item-action bg-Dpurple no-border text-white list-group-item-light p-3"
            role="button" href="#collapse2" data-bs-toggle="collapse" aria-controls="collapse1" aria-expanded="false">
            <b>>Cuentas </b> <i class="fa-solid fa-users"></i>
          </a>
        </div>
        <div class="collapse" id="collapse2">
          <a class="list-group-item list-group-item-action text-white bg-Lpurple list-group-item-light p-3 collapse-animation"
            href="{{ url_for('admin.users', page_num=1)}}">
            <b>> Usuarios</b>
          </a>
          <a class="list-group-item list-group-item-action text-white bg-Lpurple list-group-item-light p-3"
            href="{{ url_for('admin.enterprises', page_num=1)}}">
            <b>> Negocios</b>
          </a>
        </div>

      </div>
    </div>
    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
      <!-- Top navigation-->
      <nav class="navbar navbar-expand-lg navbar-light no-border bg-light border-bottom"
      style="background:#944ac5 !important;">
      <div class="container-fluid">
        <button class="btn buttonB text-white" id="sidebarToggle"><i class="fa-solid fa-bars"></i></button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            
            <div class="dropdown col-2">
              <a class="text-decoration-none text-white d-flex align-items-center fw-bold dropdown-toggle" href="#"
              role="button" data-bs-toggle="dropdown" aria-expanded="false">

              
              {% block admin_profile %}
                
              {% endblock admin_profile %}
              
            </a>
            
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Cerrar sessión</a></li>
            </ul>
          </div>

        </div>
      </nav>
      <!-- Page content-->
      
      <div class="container-fluid contener col-12">
        {{render_messages(messages)}}  
        {% block content %}
        
        {% endblock %}

      </div>
    </div>
  </div>

  <style>
    .no-border {
      border-color: rgba(0, 0, 0, 0) !important;
    }

    a {
      text-decoration: none;
    }
    .dropdown:hover .dropdown-menu {
      display: block;
      transition: all ease-out 2s !important;
    }
  </style>
</body>

<script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
<script src="{{ url_for('static', filename='js/sidebar.js') }}"></script>
<script src="https://kit.fontawesome.com/d76d9d2ca0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>

templates/enterprise_base.html
{% from '_render_elements.html' import render_messages %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href={{ url_for('static', filename='css/style.css' ) }}>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light col-12" style="height:90px; background:#7f4ca5;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('enterprises.homepage', page_num = 1)}}">
        <img width="180px" height="80px" src={{ url_for('static', filename='imgs/logo-white.png' ) }} alt="">
      </a>
      <div class="col-7">
        <form action="{{url_for('search')}}" method="POST" class="form-new">
          {{ csrf_token }}
          <input type="search" placeholder="Search" name="search" class="search-field"/>
          <button type="submit" class="search-button">
            <h5 style="font-size:20px;"><i class="fa-solid fa-magnifying-glass"></i></h5>
          </button>
        </form>
      </div>
  
      <div class="dropdown col-2">
        <a class="text-decoration-none text-white d-flex align-items-center fw-bold dropdown-toggle" href="#"
          role="button" data-bs-toggle="dropdown" aria-expanded="false">
  
          {% if sessionUser.logo == None %}
          <img width="40px" style="margin-right:10px; padding:0; background: #887edd52;" src="{{ url_for('static',
            filename='imgs/user_default.png' ) }}" alt="">
          {% else %}
          <img style="width:40px; height:40px; background: #887edd52; margin-right:10px; padding:0; object-fit:cover;"
          src="{{ url_for('picture_enterprise_profile', filename=sessionUser.logo) 
                                  if sessionUser.logo else 
                                  url_for('picture_profile', filename='none') 
                              }}"
            alt="">
          {% endif %}
          {{sessionUser.name}}
        </a>
  
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{{url_for('profile',id=sessionUser.id, page_num=1)}}">Ver perfil</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{{url_for('auth.enterprise_logout')}}">Cerrar sessión</a></li>
        </ul>
      </div>
    </div>
  </nav>

  {{render_messages(messages)}}
  {% block content %}

  {% endblock content %}

</body>


<script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
<script src="https://kit.fontawesome.com/d76d9d2ca0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

templates/landing_page.html
{% extends "void_base.html" %}

{% block content %}
<div class="contener">
    <div class="col-12 d-flex justify-content-center align-items-center opacity-75"
        style="height:30rem; background:#7166d6;">
        <img src="{{ url_for('static', filename='imgs/logo-white.png' ) }}" alt="">
        <br>
        <h3 class="text-white opacity-50" style="background:#7166d6;">Tu catalogo de confianza</h3>
    </div>
    <div class="col-12 d-inline-flex"> 
        <a href="{{url_for('auth.user_login')}}" class="btn buttonB text-white col-6" 
        style="border-radius: 0%; border-right:1px solid #ffffff;">
            Entrar como usuario
        </a>
        <a href="{{url_for('auth.enterprise_login')}}" class="btn buttonB text-white col-6" style="border-radius: 0%;">
            Entrar como empresa
        </a>

    </div>
    <div class="container col-10 mt-5">
        <div class="col-12">
            <h3 class="text-white text-center">Empresas Afiliadas con nosotros</h3>
            <hr>
            <div class="d-flex flex-wrap">
                {% for enterprise in enterprises %}
                <div class="card-title product-title">
                    <div class="card col-3 rounded-3 product_card text-white mb-4"
                        style="margin-left:2rem !important; margin-right:2rem; width:16rem !important;">

                        <div class="d-flex justify-content-center">
                            <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;" src="{{ url_for('picture_enterprise_profile', filename=enterprise.logo) 
                                    if enterprise.logo else 
                                        url_for('picture_enterprise_profile', filename='user_default.png') 
                                    }}" alt="">
                        </div>
                        <div class="card-body">
                            <span class="fw-bold">{{enterprise.name}}</span>
                            <br>
                            <span class="opacity-75">Empresa</span>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/search.html
{% if is_user==True %}
{% extends 'user_base.html' %}

{% else %}
{% extends 'enterprise_base.html' %}
{% endif %}

{% block content %}
<div class="container-fluid contener">
    <div class="text-white mb-5 text-center">
        <br>
        <h2>Resultados para</h2>
        <h5>{{ searched }}</h5>
    </div>
    <div class="d-flex justify-content-center align-items-center mt-2">
        <div class="col-12">
            <div class="mt-2 col-12 d-flex flex-wrap">
                
                {% if enterprises %}
                
                
                <div class="col-12">
                    <h3 class="text-white text-center">Empresas</h3>
                    <hr>
                    {% for enterprise in enterprises %}
                    
                    <a href="{{url_for('profile', id=enterprise.id,page_num=1)}}" class="card-title product-title">
                        <div class="card col-3 rounded-3 product_card text-white mb-4"
                        style="margin-left:2rem !important; width:16rem !important;" >
                        
                        <div class="d-flex justify-content-center">
                            <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;"
                            src="{{ url_for('picture_enterprise_profile', filename=enterprise.logo) }}" alt="">
                        </div>
                        <div class="card-body">
                            <span class="fw-bold">{{enterprise.name}}</span>
                            <br>
                            <span class="opacity-75">Empresa</span>
                            
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
            {% endif %}
                {% if products %}
                <div class="col-12">

                    <h3 class="text-white text-center">Productos</h3>
                    <hr>
                    
                <div class="mt-2 col-12 d-flex flex-wrap">

                
                {% for product in products %}
                <a href="{{url_for('product_show', id=product.id)}}" class="card-title product-title">
                    <div class="card col-3 rounded-3 product_card text-white mb-4"
                        style="margin-left:2rem !important; max-width:16rem;">


                        {% for image in images %}
                        {% if product.id == image.product_id %}
                        <div class="d-flex justify-content-center">
                            <img class="product_img mt-3 mr-2 ml-2" style="border-radius:15%;"
                                src="{{ url_for('picture_products', filename=image.filename) }}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <span>{{product.title|truncate(40)}}</span>
                            <br>
                            {% for creator in creators %}

                            {% if product.enterprise_id == creator.id %}
                            <div class="mb-2 mt-2">
                                <a href="{{ url_for('profile',id=product.enterprise_id,page_num=1) }}"
                                    class="text-white fw-bold text-decoration-none">{{creator.name}}</a>
                            </div>
                            {% endif %}

                            {% endfor %}

                            <h4 class="fw-bold">
                                ${{product.price}}
                            </h4>

                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
            </div>
                {% else %}
                <div class="mt-5 text-center col-12">
                    <h3 class="opacity-50 text-white">No hay resultados...</h3>
                </div>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/user_base.html
{% from '_render_elements.html' import render_messages %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href={{ url_for('static', filename='css/style.css' ) }}>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light col-12" style="height:90px; background:#7f4ca5;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('users.homepage', page_num = 1)}}">
        <img width="180px" height="80px" src={{ url_for('static', filename='imgs/logo-white.png' ) }} alt="">
      </a>
      <div class="col-7">
        <form action="{{url_for('search', page_num = 1)}}" method="POST" class="form-new">
          {{ csrf_token }}
          <input type="search" placeholder="Search" name="search" class="search-field"/>
          <button type="submit" class="search-button">
            <h5 style="font-size:20px;"><i class="fa-solid fa-magnifying-glass"></i></h5>
          </button>
        </form>
      </div>
  
      <div class="dropdown col-2">
        <a class="text-decoration-none text-white d-flex align-items-center fw-bold dropdown-toggle" href="#"
          role="button" data-bs-toggle="dropdown" aria-expanded="false">
  
          {% if sessionUser.logo == None %}
          <img width="40px" style="margin-right:10px; padding:0;" src="{{ url_for('static',
            filename='imgs/user_default.png' ) }}" alt="">
          {% else %}
          <img style="width:40px; height:40px; margin-right:10px; padding:0; object-fit:cover;"
          src="{{ url_for('picture_user_profile', filename=sessionUser.logo) 
                                  if sessionUser.logo else 
                                  url_for('picture_user_profile', filename='none') 
                              }}"
            alt="">
          {% endif %}
          {{sessionUser.name}}
        </a>
  
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{{url_for('user_profile',id = sessionUser.id)}}">Ver perfil</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Cerrar sessión</a></li>
        </ul>
      </div>
    </div>
  </nav>
  
  {{render_messages(messages)}}
  {% block content %}

  {% endblock content %}

</body>
<script src={{ url_for('static', filename='js/auth.js' ) }}></script>
<script src={{ url_for('static', filename='js/countryVerify.js' ) }}></script>

<script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
<script src="https://kit.fontawesome.com/d76d9d2ca0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

templates/void_base.html
{% from '_render_elements.html' import render_messages %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/style.css' ) }}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>


    <style>
        body {
            background: linear-gradient(to right, #887edd, #b57edc);
        }

        input {
            border-radius: 45px 45px 45px 45px !important;
        }

        select {
            border-radius: 45px 45px 45px 45px !important;
        }

        label {
            font-weight: bold;
        }

        .rounded-p {
            border-radius: 45px 45px 45px 45px !important;
        }

        .buttonB {
            background-color: #7f4ca5;
        }

        .buttonB:hover {
            background-color: #a255da;
        }
    </style>
    {{render_messages(messages)}}
    {% block content %}
        
    {% endblock content %}
        
    <script src={{ url_for('static', filename='js/countryVerify.js' ) }}></script>
    <script src={{ url_for('static', filename='js/auth.js' ) }}></script>
    <script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
    <script src="https://kit.fontawesome.com/d76d9d2ca0.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>